- alias: meren
  official: True
  name: A. Murat Eren (Meren)
  tenure_start: 10/2015
  role: PI
  twitter: merenbey
  github: meren
  web: http://meren.org
  avatar: bio-meren.jpg
  email: a.murat.eren@gmail.com
  twitter: merenbey
  github: meren
  linkedin: meren
  orcid: 0000-0001-9013-4827
  phone: +1-773-702-5935
  fax: +1-773-702-2281
  skype: a.murat.eren
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9118, Chicago, IL 60637 USA
  bio: "I am a computer scientist with a deep appreciation for the complexity of life. I design algorithms and experiments to better understand microbes and their ecology."
  affiliations:
    - title: MBL Fellow
      inst: Marine Biological Laboratory
      inst_link: http://www.mbl.edu/research/mbl-fellows/a-murat-eren/
    - title: Assistant Professor
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/
    - title: Committee on Microbiology
      inst: The Biomedical Sciences Cluster at the University of Chicago
      inst_link: https://biomedsciences.uchicago.edu/

- alias: florian
  official: True
  name: Florian Trigodet
  tenure_start: 08/2019
  role: Post-doctoral Scientist
  email: trigodet.florian@gmail.com
  twitter: FlorianTrigodet
  orcid: 0000-0002-4933-2896
  github: FlorianTrigodet
  linkedin: florian-trigodet-67b351b4
  avatar: bio-florian.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I am a microbiologist by training, and as a postdoctoral researcher I am using advanced computational strategies to make sense of the microbial ecology of complex habitats."
  affiliations:
    - title: Post-doctoral Scientist
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

- alias: andrea
  official: True
  name: Andrea Watson
  tenure_start: 06/2017
  role: Graduate Student
  email: andreawatson@uchicago.edu
  linkedin: andrea-rose-watson-82079a61
  github: watsonar
  orcid: 0000-0003-0128-6795
  twitter: awatsontxt
  avatar: bio-andrea.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I am interested in combining wet lab and computational methods in a complementary way to answer microbiological questions."
  affiliations:
    - title: Graduate Student
      inst: Committee on Microbiology at the University of Chicago
      inst_link: https://biomedsciences.uchicago.edu/page/microbiology

- alias: evan
  official: True
  name: Evan Kiefl
  tenure_start: 04/2017
  role: Graduate Student
  twitter: ecneicScience
  github: ekiefl
  linkedin: evan-kiefl-825985b7
  orcid: 0000-0002-6473-0921
  email: kiefl.evan@gmail.com
  avatar: bio-evan.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I am interested in uncovering how single nucleotide variants map to functional variation in the genes of naturally-occuring microbial populations."
  affiliations:
    - title: Graduate Student
      inst: The Biophysical Sciences Program at the University of Chicago
      inst_link: http://biophysics.uchicago.edu/

- alias: ozcan
  official: True
  name: Özcan C. Esen
  tenure_start: 02/2016
  role: Software guru, local hacker
  email: ozcanesen@gmail.com
  twitter: ozcanesen
  avatar: bio-ozcan.jpg
  github: ozcan
  web: http://blog.ozcanesen.com/
  bio: "As a computer engineer I strive to utilize my expertise to investigate challenges in microbial ecology, metagenomics, and visualization of complex data."
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  affiliations:
    - title: Programmer
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

- alias: mahmoud
  official: True
  name: Mahmoud Yousef
  tenure_start: 05/2017
  avatar: bio-mahmoud.jpg
  role: Undergraduate Researcher
  email: mahmoudyousef@uchicago.edu
  linkedin: mahmoud-yousef-314198128/
  github: mahmoudyousef98
  bio: "I am interested in exploring the intersection of bioinformatics and medicine, and how bioinformatic techniques can be used to advance the quality of medicine."
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  affiliations:
     - title: Undergraduate Student
       inst: Department of Computer Science at the University of Chicago
       inst_link: https://www.cs.uchicago.edu/

- alias: matt
  official: True
  name: Matthew Schechter
  tenure_start: 10/2019
  role: Graduate Student
  email: mschechter@uchicago.edu
  avatar: bio-matt.jpg
  linkedin: matthewschechter
  orcid: 0000-0002-8435-3203
  twitter: mschecht_bio
  github: mschecht
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I am interested in combining comparative genomics and environmental metagenomics to identify genetic determinants of fitness in microbial populations in the human gut and ocean microbiome."
  affiliations:
    - title: Graduate Student
      inst: Committee on Microbiology at the University of Chicago
      inst_link: https://biomedsciences.uchicago.edu/page/microbiology

- alias: abby
  official: True
  name: Abigail Schmid
  tenure_start: 02/2016
  role: Undergraduate Researcher
  email: abigailcschmid@uchicago.edu
  avatar: bio-abby.jpg
  linkedin: abigailschmid
  orcid: 0000-0002-7685-864X
  twitter: schmidabby
  bio: "I am interested in using applied mathematics and computational techniques to answer questions about microbial life."
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  affiliations:
    - title: Undergraduate Student
      inst: Computational and Applied Mathematics
      inst_link: http://collegecatalog.uchicago.edu/thecollege/caam/

- alias: emily
  official: True
  name: Emily Fogarty
  tenure_start: 06/2018
  role: Graduate Student
  email: efogarty@uchicago.edu
  github: efogarty11
  orcid: 0000-0002-8957-9922
  avatar: bio-emily.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I am interested in developing computational and wet lab strategies to study horizontal gene transfer in the human gut microbiome."
  affiliations:
    - title: Graduate Student
      inst: Committee on Microbiology at the University of Chicago
      inst_link: https://biomedsciences.uchicago.edu/page/microbiology

- alias: karen
  official: True
  name: Karen Lolans
  tenure_start: 07/2018
  role: Senior Research Technician
  email: klolans@medicine.bsd.uchicago.edu
  linkedin: karen-lolans-b39ab0
  orcid: 0000-0003-1903-756X
  avatar: bio-karen.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "As a molecular microbiologist, I am interested in the potential that interwoven wet lab and computational strategies play in elucidating complex microbial interactions and processes."
  affiliations:
    - title: Senior Research Technician
      inst: The University of Chicago Section of Gastroenterology, Hepatology and Nutrition
      inst_link: https://medicine.uchicago.edu/sections/gastroenterology-hepatology-nutrition/

- alias: joe
  official: True
  name: Joe Runde
  tenure_start: 07/2018
  role: Physician Researcher, Gastroenterology Fellow
  email: joseph.runde@uchospitals.edu
  github: jrunde1
  avatar: bio-joe.jpg
  address: The University of Chicago, 5841 S. Maryland Ave., Rm C-474, MC 4065, Chicago, IL 60637 USA
  bio: "I am interested in genome-resolved investigations of gut metagenomes of children with inflammatory bowel disease."
  affiliations:
    - title: Pediatric Gastroenterology Fellow
      inst: Section of Pediatric Gastroenterology, Hepatology and Nutrition at the University of Chicago
      inst_link: http://pediatrics.uchicago.edu/education/fellowship/gastroenterology

- alias: iva
  official: True
  name: Iva Veseli
  tenure_start: 06/2019
  role: Graduate Student
  email: iveseli@uchicago.edu
  github: ivagljiva
  orcid: 0000-0003-2390-528
  linkedin: iva-veseli
  avatar: bio-iva.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I am a computer scientist/biologist who likes leveraging computational methods to explore biological data. Currently, I am studying biogeography and ecology of the gut microbiome."
  affiliations:
    - title: Graduate Student
      inst: The Biophysical Sciences Program at the University of Chicago
      inst_link: http://biophysics.uchicago.edu/

- alias: sam
  official: True
  name: Samuel Miller
  tenure_start: 11/2019
  role: Post-doctoral Scientist
  email: samuelmiller@uchicago.edu
  orcid: 0000-0002-2836-1401
  twitter: smiller_science
  github: semiller10
  web: https://semiller10.github.io
  avatar: bio-sam.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I study how microbes function in their environments by developing and applying computational tools to interpret data from approaches such as tRNA-sequencing, proteomics, and metagenomics."
  affiliations:
    - title: Post-doctoral Scientist
      inst: The Department of Medicine at the University of Chicago
      inst_link: http://medicine.uchicago.edu/

- alias: kiki
  official: True
  name: Kiki Füßel
  web: https://twitter.com/merenbey/status/1196919880680914944
  tenure_start: 11/2019
  role: Mood Regulator
  avatar: bio-kiki.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9118, Chicago, IL 60637 USA
  bio: "I am an environmental scientist and a passionate anthropologist. I study my environments and my humans through my somatosensory, olfactory, and gustatory systems."
  affiliations:
    - title: Therapy Dog

####################################################################################
# Non-member friends
####################################################################################

- alias: ryan
  contributor: True
  avatar: bio-ryan.jpeg
  name: Ryan Moore
  linkedin: ryan-moore-444a21b5
  role: Contributing hero and anvi'o developer
  twitter: TenderIsTheByte
  github: mooreryan
  affiliations:
    - title: Graduate Student (Wommack Lab)
      inst: Center for Bioinformatics and Comp Bio, University of Delaware
      inst_link: https://bioinformatics.udel.edu/

- alias: mike
  contributor: True
  name: Mike Lee
  avatar: bio-mike.jpg
  email: michael.lee0517@gmail.com
  github: AstrobioMike
  web: https://astrobiomike.github.io
  role: Contributing hero
  twitter: AstrobioMike
  linkedin: AstrobioMike
  affiliations:
    - title: NASA Space Biology Fellow
      inst: NASA Ames Research Center
      inst_link: https://www.nasa.gov/ames
    - title: JCVI Research Fellow
      inst: J. Craig Venter Institute
      inst_link: https://www.jcvi.org/

- alias: veronika
  avatar: bio-veronika.jpg
  contributor: True
  name: Veronika Kivenson
  role: Contributing hero
  web: http://methane.geol.ucsb.edu/Home.html
  twitter: v_kivenson
  affiliations:
    - title: Graduate Student
      inst: Earth Science, UC Santa Barbara
      inst_link: http://www.geol.ucsb.edu/

- alias: antti
  contributor: True
  email: antti.karkman@helsinki.fi
  avatar: bio-antti.png
  name: Antti Karkman
  role: Contributing hero
  github: karkman
  affiliations:
    - title: Postdoctoral researcher
      inst: University of Helsinki
      inst_link: https://www.helsinki.fi/en

- alias: elaina
  contributor: True
  avatar: bio-elaina.jpg
  name: Elaina Graham
  role: Contributing hero
  github: edgraham
  twitter: perilousUnknown
  affiliations:
    - title: Graduate Student
      inst: University of Southern California
      inst_link: https://www.usc.edu/

- alias: bryan
  contributor: True
  avatar: bio-bryan.jpg
  name: Bryan Merrill
  role: Contributing hero
  github: brymerr921
  email: bmerrill@stanford.edu
  affiliations:
    - title: Graduate Student
      inst: Department of Microbiology & Immunology, Stanford University
      inst_link: http://med.stanford.edu/microimmuno.html

- alias: julie
  guest: True
  avatar: bio-julie.jpg
  name: Julie Reveillaud
  role: Guest writer
  web: https://juliereve.wordpress.com
  twitter: JulieReve
  affiliations:
    - title: Research Scientist
      inst: INRA, ASTRE Unit, Montpellier, France
      inst_link: https://www.cirad.fr/en/our-research/research-units/animals-health-territories-risks-and-ecosystems

- alias: vincent_d
  guest: True
  avatar: bio-vincent_d.png
  name: Vincent J. Denef
  email: vdenef@umich.edu
  role: Guest writer
  web: http://www-personal.umich.edu/~vdenef/
  twitter: VJDenef
  affiliations:
    - title: Assistant Professor
      inst: Ecology and Evolutionary Biology, University of Michigan
      inst_link: https://lsa.umich.edu/eeb/

- alias: jacob_e
  guest: True
  avatar: bio-jacob_e.png
  name: Jacob T. Evans
  role: Guest writer
  email: jtevans@umich.edu
  affiliations:
    - title: Bioinformatician
      inst: Ecology and Evolutionary Biology, University of Michigan
      inst_link: https://lsa.umich.edu/eeb/

- alias: jarrod_s
  guest: True
  avatar: bio-jarrod_s.png
  name: Jarrod J. Scott
  role: Guest writer
  email: jarrod.jude.scott@gmail.com
  web: https://projectdigest.github.io/
  affiliations:
    - title: Post-doctoral Scientist
      inst: Smithsonian Tropical Research Institute
      inst_link: https://stri.si.edu/

####################################################################################
# Previous members.
####################################################################################

- alias: alon
  nick_name: Alon
  tenure_start: 10/2016
  tenure_end: 02/2020
  current_info: a Genomics Data Scientist at <a href="https://weill.cornell.edu/">Weill Cornell Medicine</a>
  contributions: Throughout his studies of the human oral cavity microbiome and its enigmatic members via genome-resolved metagenomics, he served the community with his open code and tutorials. Alon, <a href="https://twitter.com/merenbey/status/1223038960789872646" target="_blank">the very first graduate student to join our group</a>, dramatically influenced the trajectory of our science
  official: True
  name: Alon Shaiber
  role: Graduate Student
  email: alon.shaiber@gmail.com
  twitter: alon_shaiber
  github: ShaiberAlon
  linkedin: alon-shaiber
  skype: alon.shaiber
  avatar: bio-alon.jpg
  address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
  bio: "I'm a graduate student in the Bio Physical Sciences Program at UChicago. I'm fascinated by the complexity of microbial ecology and interested in applying and developing computational tools to explore it."
  affiliations:
    - title: Graduate Student
      inst: The Biophysical Sciences Program at the University of Chicago
      inst_link: http://biophysics.uchicago.edu/

- alias: quentin
  official: True
  name: Quentin Clayssen
  nick_name: Quentin
  tenure_start: 04/2019
  tenure_end: 10/2019
  role: FACCTS Visiting Scientist
  email: quentin.clayssen@gmail.com
  github: qclayssen
  linkedin: quentin-clayssen-398360139
  twitter: ClayssenQ
  avatar: bio-quentin.jpg
  current_info: a graduate student at the <a href="https://ethz.ch/en.html">ETH Zurich</a>
  contributions: He contributed to the development of an anvi'o framework for <a href="http://merenlab.org/2019/10/08/anvio-scg-taxonomy/">the rapid determination of genome taxonomy</a>
  bio: "I am a microbiologist and a bioinformatician in training interested in metagenomics. I currently am focusing on approaches for rapid placement of metagenome-assembled genomes into the tree of life."

- alias: sonny
  official: True
  name: Sonny T. M. Lee
  nick_name: Sonny
  tenure_start: 05/2016
  tenure_end: 05/2018
  current_info: an Assistant Professor of Microbial Ecology (<a href="http://www.the-lee-lab.com" target="_blank">http://www.the-lee-lab.com</a>) at the Kansas State University, Division of Biology
  contributions: He took the responsibility of leading the Fecal Microbiota Transplantation work in our lab. Sonny also was the driving force behind setting up the wet-lab component of our group
  role: Post-doctoral Scientist
  email: leet1@uchicago.edu
  avatar: bio-sonny.jpg
  bio: "I am a microbiologist studying the most interesting inhabitants of humans, coral reefs, and the ocean, and using big data to answer vexing problems of our future."

- alias: tom
  official: True
  name: Tom O. Delmont
  nick_name: Tom
  tenure_start: 10/2015
  tenure_end: 05/2018
  current_info: a post-doctoral reseracher studying microbial life at the <a href="http://jacob.cea.fr/drf/ifrancoisjacob/Pages/Departements/Genoscope.aspx">Genoscope</a> in France
  contributions: He contributed to the development of anvi'o and its application to the ocean and gut metagenomes. Tom was the very first member of our lab, and Meren and Tom have spent lots of time together thinking about new ways to make sense of metagenomic data
  role: Post-doctoral Scientist
  email: tom.o.delmont@gmail.com
  twitter: tomodelmont
  avatar: bio-tom.jpg
  skype: tom.o.delmont
  bio: "I am a microbial ecologist who seeks to understand small and large-scale ecological patterns in the microbial world. My most recent investigations focused on humans, pristine soils, and the Southern Ocean."

- alias: steven
  name: Steven Cui
  nick_name: Steven
  tenure_start: 07/2016
  tenure_end: 10/2016
  current_info: an undergraduate student studying computer science at the <a href="https://www.cs.uchicago.edu/">Department of Computer Science at the University of Chicago</a>
  contributions: He contributed to the development of tRNA-seq tools, a project that bridged Meren's and <a href="https://scholar.google.com/citations?user=R5nkatMAAAAJ&hl=en">Tao Pan</a>'s interests
  official: True
  role: Summer Student
  avatar: bio-steven.png
  email: stevencui729@gmail.com
  bio: "I am an undergraduate student at UChicago studying computer science. I look forward to tackling new and exciting computational problems in the field of bionformatics."
